### ISSUE TITLE
build/assess/dedup crash on lines that are valid JSON but not objects

### ISSUE THREAD

**Issue by 01luyicheng** [ehtishammubarik/websieve#28]
## Problem

A JSONL line that parses successfully but is not a JSON object — e.g. `[1,2,3]`, `"just a string"`, `42`, `true`, `null` — crashes `build`, `assess`, and `dedup` with an uncaught `AttributeError` traceback, instead of being warned and skipped.

This contradicts the principle in CONTRIBUTING.md's preamble: *"This pipeline fails quietly. Nothing crashes; the corpus just gets worse."* A single malformed line from a writer hiccup takes down an hours-long run.

It is also the one shape of "bad line" that the `malformed` counter from #23 (PR #27) does not yet cover: that PR catches `json.JSONDecodeError` and `TypeError`, but a non-object JSON value raises `AttributeError` in `Document.from_dict` before it can be counted.

## Reproduce

```bash
printf '{"url":"u1","text":"a real document with enough words to pass"}\n[1,2,3]\n' > shapes.jsonl
websieve build shapes.jsonl -o out/
```

```
Traceback (most recent call last):
  ...
  File ".../websieve/models.py", line 67, in from_dict
    return cls(**{k: v for k, v in d.items() if k in known})
                               ^^^^^^^
AttributeError: 'list' object has no attribute 'items'
```

The same crash occurs for `"a string"`, `42`, `true`, and `null`, and across all three commands (`build`, `assess`, `dedup`) because they share `_read_docs`.

## Root cause

`_read_docs` only catches `(json.JSONDecodeError, TypeError)`:

```python
try:
    yield Document.from_dict(json.loads(line))
except (json.JSONDecodeError, TypeError) as exc:
    print(f"warning: skipping line {lineno}: {exc}", file=sys.stderr)
```

`Document.from_dict` assumes its argument is a dict (`d.items()`), so a `list`/`str`/`int`/`bool`/`None` from `json.loads` raises `AttributeError`, which is not caught. (`TypeError` is caught, which is why a dict missing `url` — e.g. `{"html": 123}` — is handled; that path raises `TypeError` from the dataclass `__init__`.)

## Why the warning path alone is not enough

Same argument as #23: at corpus scale, "crash on the first bad line" is worse than "warn and continue," and a crash mid-run on a stream of unknown length loses the partial work. The exit should be opt-in (`--strict`), not the default.

## Possible directions

- Broaden the `except` to `(json.JSONDecodeError, TypeError, AttributeError)`, or
- Guard `from_dict` (or `_read_docs`) with `isinstance(parsed, dict)` and treat non-dict lines as malformed, or
- Validate at the `Document.from_dict` boundary and raise a typed exception that `_read_docs` catches.

The `isinstance` guard is probably the cleanest: it makes "is this a record?" explicit rather than relying on which exception `from_dict` happens to raise, and it keeps the malformed counter from #23 meaningful (a non-object line is unambiguously malformed).

## What done looks like

- [ ] A non-object JSON line (`[1,2,3]`, `"x"`, `42`, `true`, `null`) is warned and skipped, not crashed, across `build`, `assess`, and `dedup`
- [ ] When wired into `build`, it is counted in the `malformed` bucket from #23 (so `seen == kept + dropped + malformed` still closes)
- [ ] A test per non-object shape, and one asserting the run exits 0 (default) and non-zero under `--strict` once that flag exists

Worth deciding explicitly: whether `Document.from_dict` itself should raise a clearer exception (e.g. `TypeError` with a message) rather than `AttributeError`, so callers that pass it a non-dict get a useful error. This is independent of the warn-and-skip fix and can be deferred.

## Scope note

Pre-existing, not introduced by #27 (the `except` clause is untouched there). It surfaced while testing that PR. It could be folded into the `--strict` / `--max-malformed` follow-up described in #23, or fixed on its own; opening separately so the crash is tracked regardless of how the strictness work is sequenced.

**Comment by ehtishammubarik** [comment]
Taking this. Reproduced first, unchanged from your report:

```
$ printf '{"url":"...","text":"..."}\n[1,2,3]\n' > shapes.jsonl
$ websieve build shapes.jsonl -o out/
  File ".../websieve/models.py", line 67, in from_dict
    return cls(**{k: v for k, v in d.items() if k in known})
AttributeError: 'list' object has no attribute 'items'
exit=1
```

Going with your `isinstance` recommendation over broadening the `except`. Your reasoning is the deciding one: catching `AttributeError` makes correctness depend on which exception `from_dict` happens to raise today, so any future refactor inside it silently changes what counts as a malformed line. An explicit "is this a record?" check cannot drift that way, and it keeps `malformed` unambiguous.

Also doing the deferred half you flagged: `Document.from_dict` will raise a `TypeError` naming what it got, rather than an `AttributeError` from the middle of a comprehension. That is a one-line change and leaving it means the next caller to pass a non-dict gets the same confusing traceback you did. If you would rather that were separate, say so and I will split it.

`--strict` landed in #31, so the third checkbox is testable now: exit 0 by default, non-zero under `--strict`.

**Comment by ehtishammubarik** [comment]
Fixed and merged in #33. All five shapes (`[1,2,3]`, `"x"`, `42`, `true`, `null`) are now warned, skipped, and counted as `malformed` across `build`, `assess`, and `dedup`, the arithmetic still closes, and `--strict` catches them. Went with your `isinstance` recommendation over widening the `except`, for the reason you gave: catching `AttributeError` would tie correctness to whichever exception `from_dict` happens to raise today. Also did the deferred half, so it raises a `TypeError` naming what it got. Thanks for filing it separately instead of folding it into #31.
